### ISSUE TITLE
Deprecated: plgContentJComments has a deprecated constructor

### ISSUE THREAD

**Issue by TinoJ** [twister65/com_jcomments#11]
I am not sure if this is the correct place to report, but I try. I found on google, that this issue might exist since the end of 2017. Today I tried JComments for the first time ever with V3.0.7 on Joomla 3.8.11 on PHP7 and got following error at the frontend :

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; plgContentJComments has a deprecated constructor in <...>\plugins\content\jcomments\jcomments.php on line 25

Can anyone please provide advice on how to fix that on my site or is it a bug?

Best, Tino

**Comment by twister65** [comment]
Hi,
You should replace the name of your constructor (class name) by `function __constructor()` like line 27:
https://github.com/twister65/com_jcomments/blob/master/plugins/content/jcomments.php
