### ISSUE TITLE
JComments Fix for PHP 7.2

### ISSUE THREAD

**Issue by Sulpher** [twister65/com_jcomments#13]
Error with JComments and PHP 7.2:
Uncaught SyntaxError: Unexpected token < 

To fix it:
Open components/com_jcomments/tpl/default/tpl_form.php

Find:
if (count($customBBCodes)) {

Replace it to:
if (!empty($customBBCodes)) {

**Comment by Sulpher** [comment]
Oh, I used the custom theme. Perhaps all is fine with the default theme.

**Comment by twister65** [comment]
Could you explain the steps to reproduce this issue ?
I have no error with default or joomspirit theme.
I have created a custom BBcode (tweet) with php v.7.2.19.
Perhaps, I don't understand your issue...

**Comment by Sulpher** [comment]
The problem was in RND JAzure theme (RoundTheme). The patch was added to the code of theme and all works fine now, I forgot to close this ticket.
